name: deploy production
on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      NEXT_PUBLIC_SERVER_TYPE: "prod"
      NEXT_PUBLIC_APP_URL: "https://cand.moimplugin.com"
      KAKAO_JS_KEY_TEST: ${{ secrets.KAKAO_JS_KEY_TEST }}
      KAKAO_JS_KEY: ${{ secrets.KAKAO_JS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: remove node_modules
        run: rm -rf node_modules

      - name: Generate deployment package
        run: zip ./deploy.zip -r * .[^.]*

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: cand-client
          environment_name: cand-vake-invite
          version_label: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
          region: us-east-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
